### ISSUE TITLE
Cannot find module 'gulp-screeps'

### ISSUE THREAD

**Issue by ObviousTroll** [ScreepsQuorum/screeps-quorum#329]
module.js:557
    throw err;
    ^

Error: Cannot find module 'gulp-screeps'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\marco\screeps-quorum\gulpfile.js:5:15)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)

**Comment by ViezeVingertjes** [comment]
Did you do `npm install` to install all packages first?

**Comment by tedivm** [comment]
Did this resolve it? Can this be closed?
