### ISSUE TITLE
Error after clearing performance stats

### ISSUE THREAD

**Issue by PostCrafter** [ScreepsQuorum/screeps-quorum#333]
```
TypeError: Cannot read property 'programs' of undefined
   at Performance.addProgramStats (qos_performance:13:33)
   at QosKernel.run (qos_kernel:94:26)
   at Object.module.exports.loop (main:71:10)
   at __module (__mainLoop:1:52)
   at __mainLoop:2:3
   at sigintHandlersWrap (vm.js:98:15)
   at ContextifyScript.Script.runInContext (vm.js:56:12)
   at Object.exports.evalCode (/opt/engine/dist/core/index.js:1347:76)
   at Object.exports.runCode (/opt/engine/dist/game/game.js:479:24)
   at connectPromise.then.then.data (/opt/engine/dist/core/runtime/runtime.js:370:31)
```

This happens because https://github.com/ScreepsQuorum/screeps-quorum/blob/0d4fea5c43f2a02e2d7014644403a25338fe4302/src/qos/performance.js#L99
clear the memory entirely and it's only reinitialized the next tick.
https://github.com/ScreepsQuorum/screeps-quorum/blob/0d4fea5c43f2a02e2d7014644403a25338fe4302/src/qos/performance.js#L4-L9

Instead of using `delete` it might be a good idea to just reinitialize the memory entry directly.

**Comment by tedivm** [comment]
This should be resolved now- want to close this issue?
